"""create alerts table

Revision ID: 1acd54906d64
Revises: 8b6d1f39eebf
Create Date: 2026-05-11 20:57:23.993294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1acd54906d64'
down_revision: Union[str, Sequence[str], None] = '8b6d1f39eebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('original_severity', sa.Enum('low', 'medium', 'high', 'critical', name='alertseverity'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'false_positive', name='alertstatus'), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_rule_match', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('raw_findings', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('attack_tactic', sa.String(length=50), nullable=True),
    sa.Column('attack_technique', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('resolution_notes', sa.String(length=2000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_fingerprint'), 'alerts', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_alerts_rule_id'), 'alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_source'), 'alerts', ['source'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.drop_index(op.f('ix_audit_logs_actor_created'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_created'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ip_created'), table_name='audit_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_ip_created'), 'audit_logs', ['ip_address', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_created'), 'audit_logs', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_created'), 'audit_logs', ['actor_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_source'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_fingerprint'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
